vich_uploader:
    db_driver: orm
    mappings:
        book_covers:
            uri_prefix: /uploads/covers
            upload_destination: '%kernel.project_dir%/public/uploads/covers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
